    version: "0.1.0"
    pre_ci_boot: 
        image: index.alauda.cn/alaudademo11/piggymetricsiggyjava 
        tag: latest

    ci:
        - cp   config/alaudaci/settings.xml  /etc/maven/
        - cd  config
        - mvn clean package

